/*
所有mutation常量對應名稱
*/

// export const REQACCESSTOKEN = 'REQACCESSTOKEN'

export default {
    REQACCESSTOKEN : 'REQACCESSTOKEN',
    REQNEWHITSPLAYLISTS: 'REQNEWHITSPLAYLISTS',
    REQCHARTS: 'REQCHARTS',
    REQTODAYSUGGEST:'REQTODAYSUGGEST',
    SEARCHKKBOX:'SEARCHKKBOX',
    REQLISTTRACKS:'REQLISTTRACKS',
    REQYOUTUBEDATA:'REQYOUTUBEDATA',
    CLEARYT:'CLEARYT'
}